name: Lint Code

on:
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**/*.js'
      - 'frontend/**/*.jsx'
      - 'frontend/**/*.ts'
      - 'frontend/**/*.tsx'
      - 'frontend/package.json'
      - 'frontend/eslint.config.js'
  push:
    branches:
      - main
    paths:
      - 'frontend/**/*.js'
      - 'frontend/**/*.jsx'
      - 'frontend/**/*.ts'
      - 'frontend/**/*.tsx'
      - 'frontend/package.json'
      - 'frontend/eslint.config.js'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    name: ESLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        run: cd frontend && npm ci

      - name: Run ESLint
        run: cd frontend && npm run lint

      - name: Generate lint report
        if: failure()
        run: cd frontend && npm run lint:report || true

      - name: Upload lint report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: frontend/eslint-report.json
          retention-days: 30
